kind: pipeline
name: default

steps:
  - name: lint
    image: stevenxie/golinter
    settings:
      revive_config: .revive.toml
    environment:
      CGO_ENABLED: '0'
      GOPROXY: &goproxy https://goproxy.io
    volumes:
      - name: gopath
        path: /go

  - name: test
    image: golang:1.12
    commands: ["go test -race ./..."]
    environment:
      GOPROXY: *goproxy
    volumes:
      - name: gopath
        path: /go


volumes:
  - name: gopath
    temp: {}

trigger:
  event:
    exclude: ["tag"]
